// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clinical.APIs.Shared.Data;

#nullable disable

namespace clinical.APIs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Radiology.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Radiology.Models.ImagingAppointment", b =>
                {
                    b.Property<int>("ImagingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagingID"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("RadiologistID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ImagingID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RadiologistID");

                    b.ToTable("ImagingAppointments");
                });

            modelBuilder.Entity("Radiology.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.HasKey("PatientID");

                    b.ToTable("RadiologyPatients");
                });

            modelBuilder.Entity("Radiology.Models.Radiologist", b =>
                {
                    b.Property<int>("RadiologistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RadiologistID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RadiologistID");

                    b.ToTable("Radiologists");
                });

            modelBuilder.Entity("Radiology.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ImagingID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("RadiologistID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("ImagingID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RadiologistID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Admin", b =>
                {
                    b.Property<int>("Admin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Admin_ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Appointment", b =>
                {
                    b.Property<int>("Appointment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Appointment_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Doctor_ID")
                        .HasColumnType("int");

                    b.Property<int>("Nurse_ID")
                        .HasColumnType("int");

                    b.Property<int>("Patient_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ref_Num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Appointment_ID");

                    b.HasIndex("Doctor_ID");

                    b.HasIndex("Nurse_ID");

                    b.HasIndex("Patient_ID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.EHR", b =>
                {
                    b.Property<int>("EHR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EHR_ID"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalAlerts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Patient_ID")
                        .HasColumnType("int");

                    b.Property<string>("PeriodontalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRayFindings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EHR_ID");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("Patient_ID");

                    b.ToTable("EHRs");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.EHRChangeLog", b =>
                {
                    b.Property<int>("ChangeLog_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeLog_ID"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedByDoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EHR_ID")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChangeLog_ID");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ChangedByDoctorId");

                    b.HasIndex("EHR_ID");

                    b.ToTable("EHRChangeLogs");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.MedicationRecord", b =>
                {
                    b.Property<int>("Medication_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Medication_ID"));

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EHR_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Medication_ID");

                    b.HasIndex("EHR_ID");

                    b.ToTable("MedicationRecords");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Nurse", b =>
                {
                    b.Property<int>("NURSE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NURSE_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NURSE_ID");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Patient", b =>
                {
                    b.Property<int>("Patient_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patient_ID"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Middle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Patient_ID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.ProcedureRecord", b =>
                {
                    b.Property<int>("Procedure_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Procedure_ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EHR_ID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToothNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Procedure_ID");

                    b.HasIndex("EHR_ID");

                    b.ToTable("ProcedureRecords");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Stock_Transaction", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("T_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Doctor_ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Supply_ID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("T_ID");

                    b.HasIndex("Doctor_ID");

                    b.HasIndex("Supply_ID");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Supply", b =>
                {
                    b.Property<int>("Supply_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Supply_ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supply_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Supply_ID");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.ToothRecord", b =>
                {
                    b.Property<int>("ToothRecord_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToothRecord_ID"));

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EHR_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surfaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToothNumber")
                        .HasColumnType("int");

                    b.Property<string>("TreatmentCompleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentPlanned")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToothRecord_ID");

                    b.HasIndex("EHR_ID");

                    b.ToTable("ToothRecords");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.XRayRecord", b =>
                {
                    b.Property<int>("XRay_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("XRay_ID"));

                    b.Property<int>("EHR_ID")
                        .HasColumnType("int");

                    b.Property<string>("Findings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TakenBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("XRay_ID");

                    b.HasIndex("EHR_ID");

                    b.ToTable("XRayRecords");
                });

            modelBuilder.Entity("clinical.APIs.Shared.Models.ProcessedRequest", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("ProcessedRequests");
                });

            modelBuilder.Entity("Radiology.Models.ImagingAppointment", b =>
                {
                    b.HasOne("Radiology.Models.Equipment", "Equipment")
                        .WithMany("ImagingAppointments")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radiology.Models.Patient", "Patient")
                        .WithMany("ImagingAppointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Radiology.Models.Radiologist", "Radiologist")
                        .WithMany("ImagingAppointments")
                        .HasForeignKey("RadiologistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Patient");

                    b.Navigation("Radiologist");
                });

            modelBuilder.Entity("Radiology.Models.Report", b =>
                {
                    b.HasOne("Radiology.Models.ImagingAppointment", "ImagingAppointment")
                        .WithMany("Reports")
                        .HasForeignKey("ImagingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Radiology.Models.Patient", "Patient")
                        .WithMany("Reports")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Radiology.Models.Radiologist", "Radiologist")
                        .WithMany("Reports")
                        .HasForeignKey("RadiologistID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImagingAppointment");

                    b.Navigation("Patient");

                    b.Navigation("Radiologist");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Appointment", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("Doctor_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Nurse", "Nurse")
                        .WithMany("Appointments")
                        .HasForeignKey("Nurse_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("Patient_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.EHR", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Appointment", "Appointment")
                        .WithOne("EHR")
                        .HasForeignKey("clinical.APIs.Modules.DentalClinic.Models.EHR", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Patient", "Patient")
                        .WithMany("EHRs")
                        .HasForeignKey("Patient_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.EHRChangeLog", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("ChangedByDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.EHR", "EHR")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("EHR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("EHR");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.MedicationRecord", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.EHR", "EHR")
                        .WithMany("Medications")
                        .HasForeignKey("EHR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EHR");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.ProcedureRecord", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.EHR", "EHR")
                        .WithMany("Procedures")
                        .HasForeignKey("EHR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EHR");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Stock_Transaction", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Doctor", "Doctor")
                        .WithMany("StockTransactions")
                        .HasForeignKey("Doctor_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.Supply", "Supply")
                        .WithMany("StockTransactions")
                        .HasForeignKey("Supply_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.ToothRecord", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.EHR", "EHR")
                        .WithMany("Teeth")
                        .HasForeignKey("EHR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EHR");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.XRayRecord", b =>
                {
                    b.HasOne("clinical.APIs.Modules.DentalClinic.Models.EHR", "EHR")
                        .WithMany("XRays")
                        .HasForeignKey("EHR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EHR");
                });

            modelBuilder.Entity("Radiology.Models.Equipment", b =>
                {
                    b.Navigation("ImagingAppointments");
                });

            modelBuilder.Entity("Radiology.Models.ImagingAppointment", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Radiology.Models.Patient", b =>
                {
                    b.Navigation("ImagingAppointments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Radiology.Models.Radiologist", b =>
                {
                    b.Navigation("ImagingAppointments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Appointment", b =>
                {
                    b.Navigation("EHR")
                        .IsRequired();
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.EHR", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Medications");

                    b.Navigation("Procedures");

                    b.Navigation("Teeth");

                    b.Navigation("XRays");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Nurse", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("EHRs");
                });

            modelBuilder.Entity("clinical.APIs.Modules.DentalClinic.Models.Supply", b =>
                {
                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
